import React from 'react';
import clsx from 'clsx';
import { HelpCircle } from 'lucide-react';

export function Card({children,className}){return <div className={clsx('rounded-2xl border border-zinc-800 bg-zinc-900/70 shadow-xl',className)}>{children}</div>}
export function Button({children,className='',variant='primary',...props}){const v={primary:'bg-emerald-500 text-zinc-950 hover:bg-emerald-400',secondary:'bg-zinc-800 hover:bg-zinc-700',danger:'bg-red-600 hover:bg-red-500',ghost:'bg-transparent hover:bg-zinc-800 border border-zinc-700'};return <button type="button" className={clsx('px-4 py-3 rounded-xl font-semibold text-base disabled:opacity-40 transition',v[variant],className)} {...props}>{children}</button>}
export function Input({label,value,onChange,type='text',className='',help,...props}){return <label className="text-base text-zinc-400 block"><span className="inline-flex items-center gap-1">{label}{help && <Help text={help}/>}</span><input type={type} value={value} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} className={clsx('mt-1 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100',className)} {...props}/></label>}
export function Textarea({label,value,onChange,rows=3,help}){return <label className="text-base text-zinc-400 block"><span className="inline-flex items-center gap-1">{label}{help && <Help text={help}/>}</span><textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100"/></label>}
export function Select({label,value,onChange,options,help}){return <label className="text-base text-zinc-400 block"><span className="inline-flex items-center gap-1">{label}{help && <Help text={help}/>}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100">{options.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
export function Badge({children,className}){return <span className={clsx('inline-flex items-center rounded-full bg-zinc-800 px-2.5 py-1 text-sm font-bold text-zinc-200',className)}>{children}</span>}
export function Stat({label,value}){return <Card className="p-5"><div className="text-sm uppercase tracking-wide text-zinc-500">{label}</div><div className="mt-1 text-3xl font-black">{value}</div></Card>}
export function Help({text}){return <span className="group relative inline-flex align-middle"><HelpCircle size={15} className="text-zinc-500 hover:text-emerald-300"/><span className="pointer-events-none absolute left-1/2 top-6 z-50 hidden w-72 -translate-x-1/2 rounded-xl border border-zinc-700 bg-zinc-950 p-5 text-left text-sm leading-relaxed text-zinc-200 shadow-2xl group-hover:block group-focus:block whitespace-normal">{text}</span></span>}
export function ProgressBar({value,max=100}){const pct=Math.max(0,Math.min(100,(value/max)*100));return <div className="h-2 w-full rounded-full bg-zinc-800 overflow-hidden"><div className="h-full bg-emerald-400" style={{width:`${pct}%`}}/></div>}
